server:
  port: 9000
  servlet:
    context-path: /
  forward-headers-strategy: native

spring:
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            scope:
              - user:email
              - read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: email
  threads:
    virtual:
      enabled: true
  
  # TestContainers will configure these properties automatically via @ServiceConnection
  # No need to specify datasource or Redis configuration here
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  data:
    redis:
      # TestContainers will configure Redis connection automatically
      database: 0
  session:
    store-type: redis

rsa-key:
  public-key: ${PUBLIC_KEY:}
  private-key: ${PRIVATE_KEY:}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    root: INFO
    io:
      lettuce: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
